### ISSUE TITLE
unexpected program closure

### ISSUE THREAD

**Issue by yiqizhengshan** [raulgilabert/IC-helper-prototype#2]
In Windows 10 version, exactly IC helper v1.1.3, when you choose "SISA to binary and hexadecimal to control unit" and you input Registers in lowercase (ex. r1 instead of R1), the program closes immediately without any advice. This is my contribution :D
I tryed with "add r1 r2 r3" and program closed.

**Comment by raulgilabert** [comment]
Currently the program does not have support for lowercase input of SISA instructions. I am working on it.
